# Generated by Django 2.0.7 on 2018-07-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='stop_date',
            field=models.DateField(),
        ),
    ]
